- name: Enable IOMMU in GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT=
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet {{ cpu }}_iommu=on"
  notify: update grub

- name: Create vfio.conf
  ansible.builtin.copy:
    dest: /etc/modules-load.d/vfio.conf
    content: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
    mode: u=rw,g=r,o=r

- name: IOMMU interrupt mapping - 1
  ansible.builtin.copy:
    dest: /etc/modprobe.d/iommu_unsafe_interrupts.conf
    content: options vfio_iommu_type1 allow_unsafe_interrupts=1
    mode: u=rw,g=r,o=r

- name: IOMMU interrupt mapping - 2
  ansible.builtin.copy:
    dest: /etc/modprobe.d/kvm.conf
    content: options kvm ignore_msrs=1
    mode: u=rw,g=r,o=r

- name: Blacklist GPU drivers
  ansible.builtin.copy:
    dest: /etc/modprobe.d/blacklist.conf
    content: |
      blacklist nouveau
      blacklist nvidiafb
      blacklist rivafb
    mode: u=rw,g=r,o=r

- name: Add GPU to vfio
  ansible.builtin.copy:
    dest: /etc/modprobe.d/vfio.conf
    content: options vfio-pci ids={{ vendor_ids }} disable_vga=1
    mode: u=rw,g=r,o=r
  when: vendor_ids is defined

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u

- name: Reboot the host
  reboot: 
