apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onedev
  namespace: onedev
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
