apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:PsgDxc41QpaUJPqHcVA6vnxPnelz3W6rEAALhTwD8nU4PZ8y6PYyAIXt8JMr04kF0ec5M6A=,iv:NX6SVQeHgbfDY8T/+8QRYTj2St92cwQTb55xpMiGrcg=,tag:zXfiu6wrdHrLknzsqLGZPw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:29:39Z"
    mac: ENC[AES256_GCM,data:vwlQEmxsSadu/iYBwTumbAfpcl3tthGqjhKNHO5btULGVPxcmVDHKzWVoy+hv0jVihocYfTxqPN426Oj23XPBIFdeBVfNS3ANLBrdKomFfaOiO+kihuD4UVuoZlfvj9J9m6stQPGSHxYkVPDHK6WLeMCFdY/V06IqW+T2wlyg3c=,iv:FGJBut4K3p4TDSDOHErOxteEJxnU8D2ANuojps6eSwg=,tag:xrSacGsLLRJlzJMlqmPrvw==,type:str]
    pgp:
        - created_at: "2026-07-08T14:29:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzDYCsAXy2LzARAAs8y5L8VCVzJiDi9iIbl+2tJDOWVy1WRTcM4PcS/F5eC1
            UdvpMmBWfkchunMwNvxl2+ZCx7t0DyCngCOKMI+O0Iqyh5wkCVg69VSvxvtQNe0o
            f0GxURrZ+vnLv5SeKNdwQ4sy0UZzrIMvxlNtDCvwZSq3qWbDVcZXbUGt0gPNraEf
            S70dzseeh4KJ4G668vDdcAu4peSM0XjqREr4RRXogAQ08viKLaSlwUR+C4dkWUtq
            Rzwo6Urtu0P2II+dRjHvkaZRgkFtE8BZVDpYs8XMESw0kNGCHjUnjXZu2HH/ss25
            Ow9XDkOKZomrfdUyE9RSQP/4Ko+x5mg//qIGh3OiM9Bq1GIHk99SfszPe5UnG841
            TKu4QtUlJHQeG6eJHh2wXDo6KZDRxRd8HBD/VCIlYlVYo3CpOAFteT3dGjLfGaCV
            HbGVKfd/5rgwZreQv9yaPqvkhWnsqPY6xjKL+vafHtxamg1YeKtHt/zOfsXGXbj5
            mIlXysBx5xYj6wKewiPkDmlxsAWMYSXKi019K8BLizT8KywXK6tIdzB0/EneYI9k
            Bvw//VZ9NM9zSLG3V8BYdT8S3balM2GHIWT73MEpM4MzWUQJE3WyNtIpPbTxrCb8
            /xsdYp39/dyT6/a7ZEsAtnRfvYIR4sdgVs2KnbNKuHZIcoGmeWY6h1K5YUdCfrzS
            XgFp+zN6qwnlnvaulYfgVJnBRVeT38kFNLBSnEYhWYhHpnHmOXgtKCq8SxmGgAVi
            op8L4VJrKZO7N9iZxHNZgLmndlHZdCXS8TdRtgM3ZZAlRMTl1WMBKSh3LsNhPP8=
            =qPGk
            -----END PGP MESSAGE-----
          fp: 7A74284C9D0E7981143C436602FAD7B940BFD8C5
    version: 3.13.2
