apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:q5EpKgG6xPM0czlPQXpfANzgTA4O0V60v3xrcFGVr9PDDAmixtTWtOQzrnB/SRwwkS9J9Do=,iv:3o2YXfFcG36ghB1+jW3V9DzJbcwXgZoA9mrJF1OWgHE=,tag:CEogSHwrVxFkSrHWnvP7KA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T20:33:17Z"
    mac: ENC[AES256_GCM,data:FVSKY6tKHzoMOE/vodDz+nXw90puGua4S/6K98kEPsEUwEOs8A6BtmVjIfKj1P9WILljfjiOPTUfQd2EegLuu4niHJzUifrxqexY31xHHsC0Su/SRGRwc0gYdDa1TYVKjikDOXedqRWhvrPJGFMgvs5BY8PW27xDA/M50D1k6mc=,iv:p/nNoCaiCuoS4/XWQLgExe3V6ZasxKFZKNnQvlimgmM=,tag:RI8T05d+bv91bXV6A8lLZQ==,type:str]
    pgp:
        - created_at: "2026-07-07T20:33:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzDYCsAXy2LzAQ//dwve0ePtNUr8CkMLedch+s3XOcB39Op4VBFt59qv4YGh
            aUt91lk4+AJdsf5TufTPLeLhAwC5nLGjsWFG4iqqhbdITzkWgIA58nPxXxy8gIOl
            7+6jWfmlT6bgJ7h/9fvCmBe/fYL2DJVueyj+eqgLHIx0RxwHWynuYW8XvfbA580b
            W4Das5QiWLXoIVUXxvVBxHLqLA6hPCoZPYbnsVJbR3z+Jv9k3rvoIe4gbQ67egI5
            2ERlmj4Mkkpeqynr5jLHpfjA3QnhmtBopSnblzSsBJFDWluII6O8UB21ExrLQ/KO
            Thl/uc6b6eEGUfh8jgRlWRnNF9WpmH+geDuH1IccHJPoLlXg0wPac4uTcecz7vNt
            yGM7ZVCdJp66qYIdp8EEuQDbMEE1DDx5laqbxd0K8a5DoVsHbDj5QuSu0xFaRMP0
            sPsjPQnIfcZwMo0z3srxpghaQSNIMnipFgL1gewySS4u76gTX5KLVAk09Ii8tYn6
            xTfqBzDjRPV7ANQ3lxelOAD1cOKN1aL57yHlj3kWjQVffFkEejX24ZqmgghliiqL
            zWli9pXAxWw6psIBfqdXUj+GYhEz1Bwa9CV4tGeH/FKq9UHta41xqO/yUHhTaUAm
            44fvidPGUReE/O460BwGnznVDScsvas2Qsi+AlYjc5aBqQVyeA1qqMXXk25MzHrS
            XAHbiFiNccnLr/Ul5/25omPu2kB+f3Zd77WLkntQfcyXnnfnVXE6UCvLy8upX5el
            vBeLo7CzXo+MkVdxWtp3WwTC2Wqefsw4AGhlpAXOiPf1l8pOU6nnYSUDgC0c
            =CV31
            -----END PGP MESSAGE-----
          fp: 7A74284C9D0E7981143C436602FAD7B940BFD8C5
    version: 3.13.2
