---
- name: Disable pve-ha-lrm
  ansible.builtin.systemd_service:
    name: pve-ha-lrm
    state: stopped
    enabled: false

- name: Disable pve-ha-crm
  ansible.builtin.systemd_service:
    name: pve-ha-crm
    state: stopped
    enabled: false
