---
- name: Adding disable nag post invoke
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      WEB_JS=/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
      if [ -s "$WEB_JS" ] && ! grep -q NoMoreNagging "$WEB_JS"; then
          echo "Patching Web UI nag..."
          sed -i -e "/data\.status/ s/!//" -e "/data\.status/ s/active/NoMoreNagging/" "$WEB_JS"
      fi

      MOBILE_TPL=/usr/share/pve-yew-mobile-gui/index.html.tpl
      MARKER="<!-- MANAGED BLOCK FOR MOBILE NAG -->"
      if [ -f "$MOBILE_TPL" ] && ! grep -q "$MARKER" "$MOBILE_TPL"; then
          echo "Patching Mobile UI nag..."
          printf "%s\n" \
            "$MARKER" \
            "<script>" \
            "  function removeSubscriptionElements() {" \
            "    // --- Remove subscription dialogs ---" \
            "    const dialogs = document.querySelectorAll('dialog.pwt-outer-dialog');" \
            "    dialogs.forEach(dialog => {" \
            "      const text = (dialog.textContent || '').toLowerCase();" \
            "      if (text.includes('subscription')) {" \
            "        dialog.remove();" \
            "        console.log('Removed subscription dialog');" \
            "      }" \
            "    });" \
            "" \
            "    // --- Remove subscription cards, but keep Reboot/Shutdown/Console ---" \
            "    const cards = document.querySelectorAll('.pwt-card.pwt-p-2.pwt-d-flex.pwt-interactive.pwt-justify-content-center');" \
            "    cards.forEach(card => {" \
            "      const text = (card.textContent || '').toLowerCase();" \
            "      const hasButton = card.querySelector('button');" \
            "      if (!hasButton && text.includes('subscription')) {" \
            "        card.remove();" \
            "        console.log('Removed subscription card');" \
            "      }" \
            "    });" \
            "  }" \
            "" \
            "  const observer = new MutationObserver(removeSubscriptionElements);" \
            "  observer.observe(document.body, { childList: true, subtree: true });" \
            "  removeSubscriptionElements();" \
            "  setInterval(removeSubscriptionElements, 300);" \
            "  setTimeout(() => {observer.disconnect();}, 10000);" \
            "</script>" \
            "" >> "$MOBILE_TPL"
      fi
    dest: /usr/local/bin/pve-remove-nag.sh
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Add no nag script
  ansible.builtin.copy:
    content: |
      DPkg::Post-Invoke { "/usr/local/bin/pve-remove-nag.sh"; };
    dest: /etc/apt/apt.conf.d/no-nag-script
    mode: u=rx,g=r,o=r
  become: true

- name: Reinstall proxmox-widget-toolkit
  ansible.builtin.command: apt --reinstall install proxmox-widget-toolkit
  become: true