---
- name: Set debian apt sources
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: http://deb.debian.org/debian/
      Suites: trixie
      Components: main contrib
      Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

      Types: deb
      URIs: http://deb.debian.org/debian/
      Suites: trixie-updates
      Components: main contrib
      Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

      Types: deb
      URIs: http://security.debian.org/debian-security/
      Suites: trixie-security
      Components: main contrib non-free-firmware
      Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
    dest: /etc/apt/sources.list.d/debian.sources
    mode: u=rw,g=r,o=r
  become: true

- name: Add pve-no-subscription repository
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pve
      Suites: trixie
      Components: pve-no-subscription
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
    dest: /etc/apt/sources.list.d/proxmox-no-subscription.sources
    mode: u=rw,g=r,o=r
  become: true

- name: Add disabled ceph repositories
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/ceph-squid
      Suites: trixie
      Components: no-subscription
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
      Enabled: false
    dest: /etc/apt/sources.list.d/ceph.sources
    mode: u=rw,g=r,o=r
  become: true

- name: Disable non free firmware warning
  ansible.builtin.copy:
    content: APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";
    dest: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
    mode: u=rw,g=r,o=r
  become: true

- name: Update package repositories
  ansible.builtin.apt:
    update_cache: true
  become: true