apiVersion: v1
data:
    username: ENC[AES256_GCM,data:owz40vUNCR0=,iv:gx/RCo1qxlg90zMRqAE+FTDAM1gZxk4bcH5BJIW2sN8=,tag:4+G/XtOjHji5+M2C1wKuLg==,type:str]
    password: ENC[AES256_GCM,data:vEBBA03SMNPAtCu49p3eTDz2kud2QHuXoBznLmsbrAk=,iv:R3q6+bCsyPIj4mg8mvvVy58X/oUf+RuYUy3BxRiR4Ac=,tag:9wKDm50es8zJvlcPROYKvA==,type:str]
kind: Secret
type: Opaque
metadata:
    name: smb-creds
    namespace: smb-system
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T08:20:40Z"
    mac: ENC[AES256_GCM,data:pBv7+PlLxiqnWIiKQ7KAIcsxXbBvUCyul1/POmRwdK17kX/6Wtmky1EQR937iMbIFhlVj3jL56V20OjGRg752kG9nzWX8z+cEGGgQx3igrI8TyfONpD7C0aXAiLGWhtCbXkYb8ZTRz4CBp91pRaUarqBqvTmkGIFJY1Lyb4NYoQ=,iv:2poniZZq0QdmTRq6jCm2G9qyorANkoqEhJ5FMliM2RU=,tag:a66/UbGQt0BuQsM/g1KJHg==,type:str]
    pgp:
        - created_at: "2026-07-07T08:20:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzDYCsAXy2LzAQ/+MzBQUKfQq3pgoE5wB5rFGRUB4nCunWuA2usE9vWhg6Vu
            6mVdgfHuH1AxOm9wzic/GQ3w9+UoMiGUZx/2gPiUFn5ThvsXZbXGQ6uVooAAGOoz
            nEoKNSFgpJCyZ97/akVgKfQkG/S/LZyYODV2eEtwHN6G/BG3HuWLLkgpA+tc00r+
            Wcrpw6ToCUlyhXcLeEaRn1XdPQBFPChih8Tjka58f6SE3FskYeTZSQBQYLdi5ozR
            O5CqEc1rXQ2uYRJ9o/IrQ5ouE/CUE1w5iv0dRqrMH8XWe6KgOXZjFekOlI8OXf9A
            JfhqtSKMBU+EI6ZWrSPGtiXH2bSO4p1ojwMK8RAK40K27aSEdVqAWOLSRPvnjDs9
            nw3vH54xbdTktGMXwCQuF2aXKIsGKam96sd1su8MQT9YbQo/if+R0mgHwQhn1YTC
            cncC8CGNCfmybx3/Q70rhvNk7JQysEgvitAVuuUgxpVWvxvIZ/2tx7LpLxYsT+yx
            E88r1mOVfwqMa3E6emjClZfkG0JfgPWq14V5Li0TQSav213t7Z1FMvIysuwH8L9n
            SNoSG/t4roNJeLc/mNotxdVaRvTfjfOQa3bO5QFW3IO2bUKQVf0Drpy2v0MZe+I1
            hcLJmq81GkBJaTzpmvVc3l1t3/DyIdRmh3AedIVr8c8lmKQpoLydRPsX+Q9Kz4rS
            UQHcosY95Cc5+Vv9+WboQbU/7NgeD3HUQErYSgMSNc7VJbY3SYKu2m6aXW78NrDj
            5T0KrWzbBU+tMCAlMChF/1ZIYfzcI55+Iq1EA/usx7GOIQ==
            =ASAv
            -----END PGP MESSAGE-----
          fp: 7A74284C9D0E7981143C436602FAD7B940BFD8C5
    version: 3.13.2
