apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5EvdYt/xMjGMKHLCD6u3RcczFAkWHv5F7vqg+jeXcTd8cBcqjXwEIci7mekhfvqAkmRu8WWNx4R/Wn3IbF79Nw==,iv:eWW+094gAurCpJ7KcM6tbhpS76LilOug/rFyk14uKyA=,tag:0pjnzOF6EpjK0bLeYyTS/w==,type:str]
    username: ENC[AES256_GCM,data:ixjurtFeX4M=,iv:zNpZ8BdzNiz8Xy5awFFpiJ1ezCuJfmYcT34cSWdhOMU=,tag:JSfKyW4Mzy4J2RuGp9IEmA==,type:str]
kind: Secret
metadata:
    name: smb-creds
    namespace: smb-system
sops:
    lastmodified: "2025-07-14T17:55:18Z"
    mac: ENC[AES256_GCM,data:tRJIszrVH2LMzMq0o/xQJUG5jSCQMwCvfU4jvEK9OoU5louKg2X8FWNZRFTdwtX+D4EQplfGGrbPKi/ic1e85IdiNke+ElyTG4i/kHbCESJhWP8+A4v5Pfi05VuhPySpzO46a5m0DC6GJWCWYazOSA6qQauxD6tpl6ybu5/4ZnA=,iv:hMdC6iXO8qVsthZbX5K7TJB15bT/eq4ZssYAuCQC3UE=,tag:GyUT3Wjo3jcIs6I6KzW2UQ==,type:str]
    pgp:
        - created_at: "2025-07-14T17:55:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxPsHDHq87wsAQ/+Oc9jjv2paPtnxXM3moqd0CC2LrQbVuYEiuScMd4kxrec
            +RbkE59h0lYjBrrtv0PqBephbZsrLumL5XUeGT9d9e08XtFsS1TESBxayc8kWOBF
            AruozFd4lumqQmxmjRZ+E8FR5H0rig174kyv5jSAXb4FESNfrT4WZ/3RqWz2wVjr
            CZArWGahhBJNdXTbKQfY2+j+qmXRXY328YETJlVuZYSJ3JtBi7wpIaxuAxERYFaS
            9kd+YLbWpr2OiRsLHgCfiI8/0ai3HZXZOq9nWJorNZCA+dQuhDqx4zZdLuU5qa2u
            zTYqPC4JDLuiKAZVoXyQiA0tWhYYOuGrRgvDo6Ir4It6dvR5JvH/EL7mwU3LKLVD
            e/s0zP4Wrt6hfbQ7y6PFd0g5kr9YJAUnJ3cwxA1RgE/CGZrozLlmOJTlWIBh7DFh
            CGhzvi6SWhb38tNlmobLR+E1cM3iKdGQuFg2T6sbuO3AHO4rvpMbpkJcRaRKaO0J
            XbuZ3yxa86ZzARBTYzjOySibyesNNmmHtkiLOGEayB4MJdsdJXr3qePh0E7QtwP2
            bpC51RQ2apiqRN5XfCTkY8c/2jZYeXnTbzKAdnFh9Atq2aXWOUzWYR4KXx+auo3Y
            RU7bp5Xr6Qmj6bjhSNJONeNP8SYEG/8WbhwJa6TNh6cpxC5fK81OJl/3ppXx71bS
            XAHM49RfmX3QwifzIud/OAiCmrC/S0oxxRsgGaeSABJZAR9uyhog2xPmW9Qn47DM
            NRshUzuE0u+Cd9W1IacCsZuAt4cyhVT449ipCyEk3UeztCDaLsNre4ohHGPv
            =hdKp
            -----END PGP MESSAGE-----
          fp: 6B021152E518C20179D5558C51DE92958775C0C2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
