apiVersion: v1
data:
    password: ENC[AES256_GCM,data:2aB3LIzixnAJiJzqRdhWxLYNL5gPPTPm2PTCkOMZ1/RwmMUXx5F0OSi3G5kwDDgzeFAWjU/YmSPHj+oyR4jtVA==,iv:obktmtRVsN7jHdaM/bWLQEn+dLo3il0J900mAa8Ziwk=,tag:xJ+G7UlO+puSrP3aBSLtWA==,type:str]
    username: ENC[AES256_GCM,data:STKr4Llgci4=,iv:YJa3jZjF/0dv8loNOqkQvEBiGXsSrVR/Xawc3odDiYE=,tag:PkcRJlgGW8a0w6XKSXJTtQ==,type:str]
kind: Secret
metadata:
    name: smb-creds
    namespace: smb-system
sops:
    lastmodified: "2025-07-14T14:42:37Z"
    mac: ENC[AES256_GCM,data:Nmvro8LI+0JfjtxiAZZMyz0p6hsQ8KkWHYP17bOGyDjE+s0ykWT+PXSle4PvxCtd6Td2S/q4aY0mCrqiZaUw1v7Ii9sxS4TBIbLKy0tItyk92UKZJXtfCQ3FYtRI48QqKTDXYrcQjmT5NhjbMxKjulKXqzBzOgZfr1d4uXiPPsE=,iv:cTrLIjtZoclGsR1o2lgIhiF+kWeHvFUgA6EIJAYeWto=,tag:ig3/OgGpQdJWn7MOrQRJIg==,type:str]
    pgp:
        - created_at: "2025-07-14T14:42:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxPsHDHq87wsAQ/+L9kVzWoTJJYPaURTnCqDmEgRAEemT4OUG7yyp3+QmWj2
            EqxNMaTEkRCxN/eWhwDgGZ4hiZHZ8ZqLaf3Dt0j5KbBDoBZfWogLiHGTjt2rCiVu
            8ty2/P1WhGu1VPocNNSQEpRWSM1IkYELEWobsxkQV/n2dXhTiFnIcYBmvSeK8GW4
            tZ07mRWAkH3enWqOIuXQNICpCBOburAhMQFqJNYNdlaqCV4O6SYQrpPlYd0P3Dvv
            DeZH9Tb9t9RvlZCYvOPX9DDT/KquExheEL0JbnmLJqAmtYcjAgy5Tec6CcXvwAyx
            gINdbZjz/yeeMWvaq6c/VAnI7Pmhn9ier4bmNtm0mugDa8SDtwX4cPJkXv7CXXR/
            rLadxbT2P9LuzQnQi3PHdTeTCVS/Qop+C08CtmHoovVYe4YZUVz8HvHao9cnBmwQ
            ZeGVsWgOPOh2CVzScadEMMnisr2BjQfcHg92vJtxnOOqt99Do9LCi2AdoRY4oSRW
            CnaG9lGXFUtkvbA1EgxpM/AqPvCCSeioyX2ijzoH37IR7aPKpx7Vfw2kQRZOl1l2
            sHWVmTQnJzOgvgo5GnsOWQ0n21NwnP2rVZB1BLawkPpu7SHX4Cbu5nZXM+wV2mNb
            HiHG5ZI0wuyQv/DGK/wqXS5ySoxLpkKxrANzPEW8sqsX588zyd1VeQZICA6jc0zS
            XgEEBoo3qEyDUDLRkWjfA3M5aQPOZBFTT9slri3UIMDJbljuoa/DQr9yN3yMRdht
            +R+/aGYKQ2WDsxYZb9eIzBKnsXUTSV/wGqdyPIh0Mx3zd/LKOWaiN9KlrGCemiI=
            =Gh96
            -----END PGP MESSAGE-----
          fp: 6B021152E518C20179D5558C51DE92958775C0C2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
