---
- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: true
  notify: Reboot

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true
  notify: Reboot

- name: Reboot
  ansible.builtin.reboot:

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Update packages
  ansible.builtin.apt:
    pkg: "*"
    state: latest
    update_cache: true
  when: update_packages
  notify: Reboot