---
- name: Install phoronix
  pacman:
    package:
      - phoronix-test-suite
    state: present
- name: phoronix install suites
  command: phoronix-test-suite install build-linux-kernel compress-7zip stockfish blender rocksdb unigine-heaven mbw vkpeak
- name: Set the /PhoronixTestSuite/Options/BatchMode/RunAllTestCombinations=FALSE
  xml:
    path: ~/.phoronix-test-suite/user-config.xml
    xpath: /PhoronixTestSuite/Options/BatchMode/RunAllTestCombinations
    value: 'FALSE'