---
- name: Wait 300 seconds
  ansible.builtin.wait_for_connection:
    timeout: 300

- name: Update VMs (apt)
  ansible.builtin.apt:
    update_cache: true
    upgrade: "{{ update_apt_upgrade_type }}"
  when: update_apt_upgrade_strategy == "apt"
  register: update_apt_update_result
