apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor-admin-secret.yaml
  - harbor-postgres-secret.yaml
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - httproute.yaml