apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: v1.17.1
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    externalURL: https://harbor.kirintor.benjaminmnoer.dk
    existingSecretAdminPassword: harbor-admin-secret
    existingSecretAdminPasswordKey: admin-password
    database:
      type: external
      external:
        host: 192.168.2.5
        port: "5432"
        username: harbor_user
        coreDatabase: harbor
        existingSecret: harbor-postgres-secret
    expose:
      type: ClusterIP
      tls:
        auto:
          commonName: "*.harbor.svc.cluster.local"