apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-secret.yaml
  - pull-secret.yaml
  - vaultwarden-admin-creds.yaml
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - httproute.yaml