apiVersion: v1
stringData:
    connectionstring: ENC[AES256_GCM,data:LAKwWqT/Ju1TMpt6NI/XbMIwqLB3dVe8j+sOwwnmfwM5nmRIhAR5D1ryAHbpctlneToyGpN3R56QVZc0Sf2foryw9jyahCeFz89YG3q6doQJat1nUM4tuftPcRtbfY4VsDHSjN0PAxX2QqpAb9+q4dOAr+LB4fp1b+Ks,iv:6vh3W2fFpxveY+vWQtn1h0XBiWvDQWuzHKtGj5vswt0=,tag:PRaRJ6GqLtZuN3d0tpYvYw==,type:str]
kind: Secret
metadata:
    name: vaultwarden-postgres-creds
    namespace: vaultwarden
type: Opaque
sops:
    lastmodified: "2025-07-22T09:16:31Z"
    mac: ENC[AES256_GCM,data:hIj2gb2Dqe1fAzqNPQSvSFMYTyfc40SPBREkjspV6jW7PmvEHaV1vdU1EwDXHv4wAKTdGb4Mma/acIndUQ/BGMJ9hMzdmiahgr4e/Fx1CMbHtMFShK1MQzgCSjExP3vXuDyp/d1L4UR9gA1UzpdVe2DqxClZjJFdqIFlKGJ/YCU=,iv:pNvSkdtQggdAB7kbyo4G8Iq0lAO5sDBotASQtr0Ux9Y=,tag:S1hsuIYm6QvyduPuzHxFtA==,type:str]
    pgp:
        - created_at: "2025-07-22T09:16:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxPsHDHq87wsAQ/7BgwyVkNIvpoBb6oWFXZgw5bv2BQt903ap6XNo/MM7nEl
            9CF0bcLZ6XJjFiy1IU1FH0G+xZRUpaWs99jqeIWrQtpxi0YODzaBET8RCwCkhqx+
            isvEZlqcfOw2Ff53CpxPcNp2TD15TApq6i537M1QVHH7IjxM5fOEKmNP6pKhj1cM
            +kjo0FQsktX/b00bXu8tZU9a/GDPN2nfFBPIBW3Hx6gj+/6W47Unl55PkvkO9v74
            /bGNbld3JT4TwmmElAP4MZ6ljtFtMugmBgM26/AcTJr/t3MwB0wfBX8MUmYiyi4E
            9e7B+oWvqJdUz8fFb0xVEvOR/Ww2DfX9ENAmeWqMW+URs3WVKcM7pjW1jkFso+WP
            VDfK2k2h5bVKlIchx8gdMCMylO0exZiXWPeT+t2ItRbFTL4k1YijISb2DdOk62BS
            3UGmKn7V64uUtDFEQcXqAnvSIdR7oiabo0z4dJ5WCaj4d20C+XAGyA1O7qHe1WKq
            Q2piC3QUZbrwU19vZqHQNcUZh71bhz0EL/cSUAXtGRoo2BP4HZuNW3ovxkSC9cA5
            l5pMLZn4ogOsL47ra4DncospjqB62CgRRwOZgP07xQgCeZ8eRn/31h2qj7U/QWjJ
            upyl0SxiJYSy7MMZdhR4OdPADi4wMzOHg9qzFd/l/xkvy5hC0IOOaP2oKK4ZqRfS
            XAGbb3KhgiNU2x6SCSyfkwT+RRuaVL+5mnJjJbp0SenWcNJLz4gyJLEVEuI9dIk6
            SCRi6KpqJjQwh0wk3lWcDo1hy2Cwni/mp6cas5iSmtEbBnk8o83/UQa5Dqxt
            =A0IP
            -----END PGP MESSAGE-----
          fp: 6B021152E518C20179D5558C51DE92958775C0C2
    encrypted_regex: ^(stringData|data)$
    version: 3.10.2
