apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    domain: "https://vault.kirintor.benjaminmnoer.dk"
    image:
      registry: harbor.kirintor.benjaminmnoer.dk/vaultwarden
      pullSecrets:
        - name: harbor-secret
    service:
      type: ClusterIP
    database:
      type: postgres
      existingSecret: vaultwarden-postgres-creds
      existingSecretKey: connectionstring
    adminToken:
      existingSecret: vaultwarden-admin-creds
      existingSecretKey: adminToken
