apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: podinfo
spec:
  serviceSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: podinfo-gateway
  externalIPs: true
