FROM archlinux/archlinux:base-devel-20260401.0.509693

# Install packages
RUN pacman -Syu --noconfirm \
    git \
    talosctl \
    kubectl \
    cilium-cli \
    opentofu \
    ansible \
    opencode
