---
- name: Enable GPU Passthrough
  hosts: gpupassthrough
  become: true
  tasks:
    - name: Enable IOMMU in GRUB
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: ^GRUB_CMDLINE_LINUX_DEFAULT=
        line: GRUB_CMDLINE_LINUX_DEFAULT="quiet {{ cpu }}_iommu=on"
      notify: Update GRUB

    - name: Create vfio.conf
      ansible.builtin.copy:
        dest: /etc/modules-load.d/vfio.conf
        content: |
          vfio
          vfio_iommu_type1
          vfio_pci
          vfio_virqfd
        mode: u=rw,g=r,o=r
      register: gpupassthrough_vfio

    - name: IOMMU enable unsafe interrupts
      ansible.builtin.copy:
        dest: /etc/modprobe.d/iommu_unsafe_interrupts.conf
        content: options vfio_iommu_type1 allow_unsafe_interrupts=1
        mode: u=rw,g=r,o=r
      register: gpupassthrough_iommu

    - name: Kvm ignore msrs
      ansible.builtin.copy:
        dest: /etc/modprobe.d/kvm.conf
        content: options kvm ignore_msrs=1
        mode: u=rw,g=r,o=r
      register: gpupassthrough_kvm

    - name: Blacklist GPU drivers
      ansible.builtin.copy:
        dest: /etc/modprobe.d/blacklist.conf
        content: |
          blacklist nouveau
          blacklist nvidiafb
          blacklist rivafb
        mode: u=rw,g=r,o=r
      register: gpupassthrough_blacklist

    - name: Add GPU to vfio
      ansible.builtin.copy:
        dest: /etc/modprobe.d/vfio.conf
        content: options vfio-pci ids={{ vendorids }} disable_vga=1
        mode: u=rw,g=r,o=r
      when: vendorids is defined
      register: gpupassthrough_gpu

    - name: Update initramfs
      ansible.builtin.command: update-initramfs -u
      when: (gpupassthrough_vfio is changed) or (gpupassthrough_iommu is changed) or (gpupassthrough_kvm is changed) or (gpupassthrough_gpu is changed)
      notify: Reboot
      changed_when: true

  handlers:
    - name: Update GRUB
      ansible.builtin.command: update-grub
      changed_when: false

    - name: Reboot
      ansible.builtin.reboot:
