---
- name: Setup Talos Kubernetes Cluster with Cilium and Flux CD
  hosts: ansible_controller
  gather_facts: true
  vars_prompt:
    - name: github_pat
      prompt: "Github PAT"
      private: true
  tasks:
    - name: Install host CLI tools
      ansible.builtin.include_role:
        name: install_cli_tools
      tags:
        - tools
    - name: Install Gateway CRDs and Cilium
      ansible.builtin.include_role:
        name: install_k8s_cluster
      tags:
        - cluster
    - name: Install Flux CD
      ansible.builtin.include_role:
        name: install_flux
      tags:
        - flux
