---
- name: Setup Talos Kubernetes Cluster with Cilium and Flux CD
  hosts: localhost
  gather_facts: true
  vars_prompt:
    - name: github_pat
      prompt: "Github PAT"
      private: true
  vars:
    cluster_name: "Kirin Tor"
    flux_git_repo: "https://github.com/benjaminmnoer/iac.git"
    flux_git_owner: "benjaminmnoer"
    flux_git_branch: "master"
    flux_git_path: "clusters/production"
  tasks:
    - name: Install host CLI tools
      ansible.builtin.include_role:
        name: install_cli_tools
      tags:
        - tools
    - name: Install Gateway CRDs and Cilium
      ansible.builtin.include_role:
        name: install_k8s_cluster
      tags:
        - cluster
    - name: Install Flux CD
      ansible.builtin.include_role:
        name: install_flux
      tags:
        - flux
