---
- name: Update Proxmox Hosts
  hosts: proxmox
  become: true
  tasks:
  - name: Gather list of VMs
    shell: qm list | awk 'NR>1 {print $1}'
    register: vm_list
    changed_when: false
  # - debug:
  #     msg: "List of VMs: {{ vm_list }}"

  - name: Stop all VMs
    command: qm shutdown {{ item }}
    loop: "{{ vm_list.stdout | split('\n') }}"
    ignore_errors: true

  # - name: Update system packages
  #   apt:
  #     update_cache: true
  #     upgrade: dist

  # - name: Reboot Proxmox host
  #   reboot:
  #     msg: "Rebooting Proxmox host after updates"
  #     reboot_timeout: 600