---
- name: Setup Local Talos Kubernetes Cluster with Cilium (Helm + CLI) and Flux CD
  hosts: localhost
  vars_prompt:
    - name: github_pat
      prompt: "Github PAT"
  vars:
    talos_version: "1.10.2"
    kubernetes_version: "1.33.1"
    cilium_version: "1.17.4"
    cluster_name: "Kirin Tor"
    flux_git_repo: "https://github.com/benjaminmnoer/iac.git"

  tasks:
    - name: Update system packages
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: Install required pacman packages
      become: true
      pacman:
        name:
          - docker
          - kubectl
          - fluxcd
          - helm
          - jq
          - wget
          - cilium-cli
        state: present

    - name: Install hubble
      become: true
      shell: |
        HUBBLE_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/hubble/master/stable.txt)
        HUBBLE_ARCH=amd64
        curl -L --fail --remote-name-all https://github.com/cilium/hubble/releases/download/$HUBBLE_VERSION/hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
        sha256sum --check hubble-linux-${HUBBLE_ARCH}.tar.gz.sha256sum
        sudo tar xzvfC hubble-linux-${HUBBLE_ARCH}.tar.gz /usr/local/bin
        rm hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
      args:
        creates: /usr/local/bin/hubble

    - name: Download talosctl checksums
      get_url:
        url: https://github.com/siderolabs/talos/releases/download/v{{ talos_version }}/sha256sum.txt
        dest: /tmp/talosctl-sha256sum.txt
        mode: u=rw,g=r,o=r

    - name: Install talosctl
      become: true
      get_url:
        url: https://github.com/siderolabs/talos/releases/download/v{{ talos_version }}/talosctl-linux-amd64
        dest: /usr/local/bin/talosctl
        checksum: "sha256:{{ checksum[0].split()[0] }}"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      vars:
        checksum: '{{ lookup("file", "/tmp/talosctl-sha256sum.txt").splitlines() | select("match", ".*talosctl-linux-amd64$") | list }}'

    - name: Add Cilium Helm repository
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io
        force_update: true

    - name: Update Helm repositories
      command: helm repo update

    # - name: Install Gateway API CRDs
    #   shell: |
    #     kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
    #     kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
    #     kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
    #     kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
    #     kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
    #     kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml

    - name: Install Cilium using Helm
      command: >
        helm install cilium cilium/cilium
        --namespace kube-system
        --set ipam.mode=kubernetes
        --set kubeProxyReplacement=true
        --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        --set cgroup.autoMount.enabled=false
        --set cgroup.hostRoot=/sys/fs/cgroup
        --set k8sServiceHost=192.168.3.3
        --set k8sServicePort=6443
        --set hubble.relay.enabled=true
        --set hubble.ui.enabled=true

    - name: Verify Cilium CLI is working
      command: cilium-cli status --wait

    - name: DNS test
      command: kubectl run -it --rm --restart=Never --image=busybox dns-test -- nslookup google.com

    # - name: Create namespace
    #   command: kubectl create namespace cilium-test-1

    # - name: Label namespace
    #   command: kubectl label namespace cilium-test-1 pod-security.kubernetes.io/enforce=privileged

    # - name: Cilium test
    #   command: cilium-cli connectivity test

    # - name: Remove namespace
    #   command: kubectl delete namespace cilium-test-1

    - name: Bootstrap Flux into Kubernetes
      command: >
        flux bootstrap github
        --owner="benjaminmnoer"
        --repository="iac"
        --branch="master"
        --path="clusters/production"
        --personal
      environment:
        GITHUB_TOKEN: "{{ github_pat }}"
