---
- name: Check if Flux is already bootstrapped
  ansible.builtin.command: flux get all -A
  register: install_flux_check
  changed_when: false
  failed_when: false

- name: Bootstrap Flux into Kubernetes
  ansible.builtin.command: >-
    flux bootstrap github
    --owner="{{ install_flux_git_owner }}"
    --repository="{{ install_flux_git_repo | regex_replace('.*/([^/]+)\\.git', '\\1') }}"
    --branch="{{ install_flux_git_branch }}"
    --path="{{ install_flux_git_path }}"
    --personal
  register: install_flux_bootstrap
  when: install_flux_check.rc != 0
  changed_when: install_flux_bootstrap.rc == 0
  environment:
    GITHUB_TOKEN: "{{ github_pat }}"
  tags:
    - flux

- name: Check if SOPS secret already exists
  ansible.builtin.command: >-
    kubectl get secret sops-gpg -n {{ install_flux_namespace }}
  register: install_flux_sops_secret_check
  changed_when: false
  failed_when: false

- name: Add decryption key
  ansible.builtin.shell: >-
    set -o pipefail &&
    gpg --export-secret-keys --armor "{{ install_flux_sops_key_fingerprint }}" |
    kubectl create secret generic sops-gpg
    --namespace={{ install_flux_namespace }}
    --from-file=sops.asc=/dev/stdin
  register: install_flux_decryption_key
  when: install_flux_sops_secret_check.rc != 0
  changed_when: install_flux_decryption_key.rc == 0
  no_log: true
  tags:
    - flux
