apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  releaseName: csi-driver-smb
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.18.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    controller:
      runOnControlPlane: true