---
install_flux_git_repo: "https://github.com/benjaminmnoer/iac.git"
install_flux_git_owner: "benjaminmnoer"
install_flux_git_branch: "master"
install_flux_git_path: "clusters/production"
install_flux_namespace: flux-system
install_flux_sops_key_fingerprint: "6B021152E518C20179D5558C51DE92958775C0C2"
