---
install_k8s_cluster_cilium_version: "1.19.3"
install_k8s_cluster_cilium_namespace: cilium
install_k8s_cluster_gateway_api_version: "v1.5.1"
install_k8s_cluster_gateway_api_base_url: >-
  https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ install_k8s_cluster_gateway_api_version }}/config/crd
install_k8s_cluster_gateway_crd_urls:
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_gatewayclasses.yaml"
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_gateways.yaml"
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_httproutes.yaml"
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_referencegrants.yaml"
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_grpcroutes.yaml"
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_backendtlspolicies.yaml"
  - "{{ install_k8s_cluster_gateway_api_base_url }}/standard/gateway.networking.k8s.io_tlsroutes.yaml"
