apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:43sY5Epxg6Y=,iv:jc4HEhIXD5cV2kD+irwIMw5WsIbVQr5OwYPXNcoX0hc=,tag:lWX1VwjjaUXha+1qfyLMDw==,type:str]
    password: ENC[AES256_GCM,data:qlZ8LiWJ7QIbsPdzCJgAEDQM9fe4u3i98GEhAD14wqI=,iv:vuJJsibZnmjc2+Qhe66c0cYDoVAC4I1/j2+qj1a3i8Y=,tag:7LxJbNNtd2PvpMIxdGfwcw==,type:str]
kind: Secret
type: Opaque
metadata:
    name: smb-creds
    namespace: smb-system
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T18:37:32Z"
    mac: ENC[AES256_GCM,data:fXw8+Ii5LpIJf/yYvOfnj3Dqd+a805a4cu6D5woUK91rcI82NUTekbsJeY4OAX7hpD4c6P6uOjOkt5gT0PAHb+0w+4yfv1FDaHOfQfkAdG+w/54eKbG6axzkB/WRFizZW2fJkZAd3frSsJIIXd0K9nHn/IwOYwWX340lVIXfBB0=,iv:BP/eBtnjhyNQPi+K251nTn5rwWjmBfSXxB/C8WlU39Y=,tag:OW5FyRqxK+a1ag+ZZo1nVQ==,type:str]
    pgp:
        - created_at: "2026-07-07T18:37:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzDYCsAXy2LzAQ//Sx7d9xfNYbmfYAW/FKIHX4nqtlGxeVkdTn2FJ+YOZCvn
            4wzbXF3zyasGA+ivkxebI0FqKirzErmtwR/5SjxQD1LmEGS7HmQ0jsX8SSyRjPrx
            iTbdQRdeMFGmNQOu+IzBWSpE+I9Y10cl1Rpp8rBKWBd7zOmjokhFxDcsWbf0nKfa
            QBbLTln0S78HWEBlOevvJknr65JQsGLJp6FETQODg0pEnLu4uCviSB9A3EOP7LiW
            6+Pu7jpBhAho+ds+7+iPdGVQMMNsYo4SVvXMsj1bdkonotiGLuSLoaGl1/pKHi4E
            8Y8A/QaqLKjeYDIk4n2jqCIMv6Ghs65h29kuw8b+VP+0uCuTprUO8uZ7DHJrr+Gw
            15D7YjXK1ct+q5cAt7/d8fSBEC6JeYQFN7ncTyXf9cCsZEOD5dVNdmz2SWd9khaJ
            UU/wVNsbpvsJ0s0jXsz+8FK6ao/dw4Np2pjsTi/yc5n4ea1lzXaZc0y8hAg+gevB
            KyVxe9MAItQvL3rsIiE95ECmTW4HSc/O2OuVqn8giFPxPG+BhODBKt50pEzVcvNA
            jATveZlVNqLf5o1TYjZ1O7t2rR5zJI4Eo2+GGGKFhM5XMpp8kpSxY0LGwmeNkx+F
            nY1lw2y2WpMu3mWanyUYqjKfGWZCsSY0vSmEsxKwLsBtEx+zmCA3NBy9iRYklMDS
            XgFA+rXCT53fApPg83jn2vSayWNGrL5eYzgp92jI4ZocGxAnhcum/uWM05Z+43Pm
            DbH3zn6TrR/fTXh05dVwSltbmzOoeBNnOOKIPX1m4cWPeJijAx86HU+26admIo0=
            =1dpb
            -----END PGP MESSAGE-----
          fp: 7A74284C9D0E7981143C436602FAD7B940BFD8C5
    version: 3.13.2
